import React from "react";

const lazyImport = (name) => React.lazy(() => import(`./projects/${name}.jsx`));

export const lazyComponentMap = {
    accordion: lazyImport("Accordion"),
    avataar: lazyImport("Avataar"),
    calculator: lazyImport("Calculator"),
    calendar: lazyImport("Calendar"),
    "canvas-animation": lazyImport("CanvasAnimation"),
    "convert-metrics": lazyImport("ConvertMetrics"),
    dictionary: lazyImport("Dictionary"),
    "digital-clock": lazyImport("DigitalClock"),
    "dynamic-tables": lazyImport("DynamicTables"),
    "github-profile-finder": lazyImport("GithubProfileFinder"),
    "html-colors": lazyImport("HtmlColors"),
    "image-slider": lazyImport("ImageSlider"),
    "jokes-generator": lazyImport("JokesGenerator"),
    "language-translator": lazyImport("LanguageTranslator"),
    "leet-speak": lazyImport("LeetSpeak"),
    "lyrics-finder": lazyImport("LyricsFinder"),
    "memes-generator": lazyImport("MemesGenerator"),
    "modal-component": lazyImport("ModalComponent"),
    "movie-search": lazyImport("MovieSearch"),
    "movie-trailer": lazyImport("MovieTrailer"),
    "mui-form": lazyImport("MuiForm"),
    "paint-app": lazyImport("PaintApp"),
    "password-generator": lazyImport("PasswordGenerator"),
    "periodic-table": lazyImport("PeriodicTable"),
    "qrcode-generator": lazyImport("QrcodeGenerator"),
    "quiz-app": lazyImport("QuizApp"),
    "random-quotes": lazyImport("RandomQuotes"),
    "rock-paper-scissor": lazyImport("RockPaperScissor"),
    "scroll-progress-indicator": lazyImport("ScrollProgressIndicator"),
    "scroll-to": lazyImport("ScrollTo"),
    "search-auto-complete": lazyImport("SearchAutoComplete"),
    sorting: lazyImport("Sorting"),
    "star-rating": lazyImport("StarRating"),
    sudoku: lazyImport("Sudoku"),
    "task-scheduler": lazyImport("TaskScheduler"),
    "tic-tac-toe": lazyImport("TicTacToe"),
    "to-do-list": lazyImport("ToDoList"),
    "toggle-theme": lazyImport("ToggleTheme"),
    "typing-keyboard": lazyImport("TypingKeyboard"),
    "unicode-explorer": lazyImport("UnicodeExplorer"),
    validators: lazyImport("Validators"),
    "weather-app": lazyImport("WeatherApp"),
    "word-meaning": lazyImport("WordMeaning"),
    "world-map": lazyImport("WorldMap"),
    "world-time-zones": lazyImport("WorldTimeZones"),
};
